[package]
name = "MDocsR"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
bcrypt = "0.19.1"
rand = "0.10.1"
hex = "0.4.3"
config = "0.15.23"
serde = "1.0.228"
jsonwebtoken = "10.4.0"

[dependencies.uuid]
version = "1.23.2"
# Lets you generate random UUIDs
features = [
    "v4",
]
